### ISSUE TITLE
Pixel Format toString() conversions

### ISSUE THREAD

**Issue by kbingham** [KaairaGupta/libcamera#1]
Initial patches have been submitted to convert pixel-formats to string.
This task serves to track progress, and completion of those implementations.

Current note (I'll review on the patches directly) is that after discussion with Laurent we need to simplify the patches, as DRM provides many modifiers which are irrelevant to us.
We need to simplify and print cases that are relvevenat to us, while perhaps just printing an unconverted value for non-used cases.

In all cases we should print the vendor though, to highlight which modifier the code relates to.

**Comment by KaairaGupta** [comment]
Waiting for 'libcamera::formats:: namespace' proposal to be finalised.

**Comment by KaairaGupta** [comment]
Patches affected: 
- https://lists.libcamera.org/pipermail/libcamera-devel/2020-June/009055.html
- https://lists.libcamera.org/pipermail/libcamera-devel/2020-May/008969.html

**Comment by kbingham** [comment]
v4 "v4l2subdev: Print mbus string instead of code" looks like it's ready to merge to me. I'll push it. Laurent hasn't added a tag, but his comments have been addressed.

**Comment by KaairaGupta** [comment]
Closes with: https://git.linuxtv.org/libcamera.git/commit/?id=2129117df920699ad83bd231ebe83ca9f0a619da
