### ISSUE TITLE
Fix the current format flow in VIMC links

### ISSUE THREAD

**Issue by KaairaGupta** [KaairaGupta/libcamera#6]
Currently for qt<5.14, VIMC pipeline handler picks up 'V4L2_PIX_FMT_SGRBG8' at the sensor, which the VIMC should support. But the pipe ends up breaking due to the difference in Scaler's source (RGB3) and Capture's sink (BGR3) formats. This should be fixed

**Comment by kbingham** [comment]
I think we can close this one as fixed by the QCam pixel format ordering patch?
