### ISSUE TITLE
VIMC: Colour descriptions

### ISSUE THREAD

**Issue by kbingham** [KaairaGupta/libcamera#7]
It's hard to tell when the VIMC test pattern is ordered incorrectly.

Investigate the possibility of adding text to each colour bar of the VIMC test pattern to mention it's colour.

The vivid driver has an example of how to write text on an image, so it may help there.

**Comment by kbingham** [comment]
Dicussion thread started on linux-media mailing list

**Comment by KaairaGupta** [comment]
RFC link: https://patchwork.linuxtv.org/patch/64349/

**Comment by KaairaGupta** [comment]
Closes with:
https://git.linuxtv.org/media_tree.git/commit/?id=5f3fb5c54d67670fa6743d2434a5bd43a97c01de
https://git.linuxtv.org/media_tree.git/commit/?id=7a785081a16968a28adce223c572111d2d57a83e
https://git.linuxtv.org/media_tree.git/commit/?id=9dc75e79c0dec0eb9363793efbd5f16d134169dc
